#!/bin/bash

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.

set -e
set -o errexit
set -o errtrace

cd $(dirname $0)/..

bundle exec htmlproof ./_site --disable-external