#!/bin/bash

# script/vagrant: Setup vagrant environment after cloning

set -e
set -o errexit
set -o errtrace

cd $(dirname $0)/..

source /vagrant/script/settings

/vagrant/script/bootstrap

if [ ! -d $HOME_DIR ]
then
    ln -s /vagrant $HOME_DIR
    cd $HOME_DIR
fi

echo " cd ${HOME_DIR}" | sudo tee -a /home/vagrant/.bash_profile
cp /vagrant/.inputrc /home/vagrant
cp /vagrant/.vimrc /home/vagrant
chown -R vagrant:vagrant /home/vagrant
